feat: use user tags to check PSA auth
web3-storage/web3.storage pull request #1008
Opened 2022-02-18 15:36 UTC by alexandrastoica

Removes the old `pinning_authorization` table and uses user tags instead

2022-02-21 11:54 UTC, flea89 commented on packages/api/test/fixtures/init-data.sql
> +-- -- user 'test-pinning' is authorized
nit: double comment -- --

2022-02-21 18:11 UTC, trigramdev9 requested changes

2022-02-21 18:11 UTC, trigramdev9 commented on packages/api/test/fixtures/init-data.sql
> +        (5, 'PSA_ENABLED', true, 'boolean', 'test');
please pull the latest.  `value_type` has been removed.

2022-02-21 18:11 UTC, trigramdev9 commented on packages/db/postgres/pg-rest-api-types.d.ts
> +    tag: "ACCOUNT_ENABLED" | "PSA_ENABLED" | "STORAGE_LIMIT_BYTES";
please pull latest.  these have been renamed.

2022-02-21 18:11 UTC, trigramdev9 commented on packages/db/index.js
> +      .eq('tag', 'PSA_ENABLED')
please pull latest.  this has been renamed to `HasPsaAccess`

2022-02-23 11:26 UTC, alexandrastoica commented
SQL for migrating the existing data from `pinning_authorization` to `user_tag`

```
BEGIN TRANSACTION;
INSERT INTO public.user_tag
(
    user_id,
    tag,
    value,
    reason,
	inserted_at
)
SELECT
     user_id,
     'HasPsaAccess' as tag,
     'true' as value,
     'Approved access' as reason,
	 inserted_at
 FROM public.pinning_authorization
 WHERE deleted_at IS NULL;
 
INSERT INTO public.user_tag
(
    user_id,
    tag,
    value,
    reason,
	inserted_at,
	deleted_at
)
SELECT
     user_id,
     'HasPsaAccess' as tag,
     'false' as value,
     'Revoked access' as reason,
	 inserted_at,
	 deleted_at
 FROM public.pinning_authorization
 WHERE deleted_at IS NOT NULL;

DROP TABLE public.pinning_authorization;
COMMIT;
```

2022-02-24 16:23 UTC, alanshaw commented
@alexandrastoica could you add the migration SQL to here please? https://github.com/web3-storage/web3.storage/tree/main/packages/db/postgres/migrations

2022-02-24 16:51 UTC, flea89 commented
@alanshaw thanks for pointing that out! We noticed this morning that folder was created 🎉 

While I understand this is not the full, polished solution for migrations, (since we're still missing the automation side of it) I do believe moving migrations scripts to version control is a great improvement to what we're doing now. 
So big plus and thanks 🙏  ! 

I'm wondering if we should be adding some documentation to make sure developers know what's expected when altering schemas?

Do we have an issue to track the more holistic DB migration epic/approach?

2022-02-25 16:34 UTC, alexandrastoica commented
@alanshaw added the migration file. Let me know if this is ok to merge. Thanks!

2022-03-04 13:27 UTC, alanshaw approved these changes
LGTM

2022-03-04 14:04 UTC, merged

2022-03-09 14:33 UTC, vasco-santos commented
Runing SQL migration for deploy got:

```
web3-storage-prod::HEROKU_POSTGRESQL_AQUA=> INSERT INTO public.user_tag
(
    user_id,
    tag,
    value,
    reason,
    inserted_at
)
SELECT
    user_id,
    'HasPsaAccess' as tag,
    'true' as value,
    'Approved access' as reason,
    inserted_at
 FROM public.pinning_authorization
 WHERE deleted_at IS NULL;
ERROR:  invalid input value for enum user_tag_type: "HasPsaAccess"
LINE 11:     'HasPsaAccess' as tag,
```
Looking into it

2022-03-09 14:36 UTC, flea89 commented
@vasco-santos the user_tag enum was created as part of a separate PR from trigram folks, it's possible they haven't created a migration to create the ENUM?
```
-- User tags are associated to a user for the purpose of granting/restricting them
-- in the application.
CREATE TYPE user_tag_type AS ENUM
(
  'HasAccountRestriction',
  'HasPsaAccess',
  'StorageLimitBytes'
);
```

2022-03-09 16:43 UTC, trigramdev9 commented
> @flea89 thanks, you were right! The type was outdated and it was merged without updating the type. We need to improve communication on DB changes

@vasco-santos i'll take ownership for this in this instance.  if you recall the conversations we were having a few weeks ago about naming...  i meant to follow up once we were all in agreement and the conversations had died down to avoid unnecessary DB updates in prod, but i forgot to do so.