chore: update client examples
web3-storage/web3.storage pull request #103
Opened 2021-07-19 10:33 UTC by vasco-santos

TODO:

- [ ] have `files-from-path` exported in the client

2021-07-19 15:02 UTC, alanshaw requested changes

2021-07-19 15:02 UTC, alanshaw commented on packages/client/examples/node.js/put-files.js
> +  const endpoint = args.endpoint || defaultEndpoint
I would remove any endpoint stuff - just noise to new users.

2021-07-19 15:02 UTC, alanshaw commented on packages/client/examples/browser/README.md
> +A demo using web3.storage client in the browser to pre-calculate the CID for an asset then storing it on web.storage.
```suggestion
A demo using web3.storage client in the browser to pre-calculate the CID for an asset then store it on web3.storage.
```

2021-07-20 07:14 UTC, vasco-santos commented on packages/client/examples/node.js/package.json
> +    "web3.storage": "../.."
Do you know if npm workspaces will deal with updating it? Changing it for now as you suggest

2021-07-20 14:20 UTC, alanshaw requested changes

2021-07-20 14:20 UTC, alanshaw commented on packages/client/examples/node.js/put-files-from-fs.js
> +const endpoint = 'https://api.web3.storage'
Can you remove this as well please? Unnecessary for users to pass it.

```suggestion
```

2021-07-20 14:20 UTC, alanshaw commented on packages/client/examples/node.js/put-files-from-fs.js
> +  const storage = new Web3Storage({ endpoint, token })
```suggestion
  const storage = new Web3Storage({ token })
```

2021-07-20 14:20 UTC, alanshaw commented on packages/client/examples/node.js/put-files.js
> +const endpoint = 'https://api.web3.storage'
```suggestion
```

2021-07-20 14:20 UTC, alanshaw commented on packages/client/examples/node.js/put-files.js
>    const storage = new Web3Storage({ endpoint, token })
```suggestion
  const storage = new Web3Storage({ token })
```

2021-07-20 14:56 UTC, alanshaw approved these changes

2021-07-20 16:53 UTC, merged