fix: store IPFS peer IDs
web3-storage/web3.storage pull request #1093
Opened 2022-03-09 17:58 UTC by alanshaw

Reverts https://github.com/web3-storage/web3.storage/pull/966 and instead stores the IPFS peer ID in the `pin_location` table.

2022-03-09 19:11 UTC, vasco-santos requested changes
Thanks for putting this together really fast Alan ❤️

2022-03-09 19:11 UTC, vasco-santos commented on packages/db/postgres/migrations/003-add-ipfs-peer-ids.sql
> +UPDATE pin_location SET peer_id='12D3KooW9yCAQ2edw5N75b7t9qCGYb7uFVzkfAgp4KoyTEJKXenF', ipfs_peer_id='12D3KooWJEfH2MB4RsUoaJPogDPRWbFTi8iehsxsqrQpiJwFNDrP' WHERE peer_id='12D3KooWJEfH2MB4RsUoaJPogDPR
We need to add the new peers recently added. DB Table currently has 15

2022-03-09 19:56 UTC, alanshaw commented on packages/cron/src/jobs/pins.js
> +      let pinInfo = peerMap[pin.location.peerId]
I will pause the cron when we start maintenance tomorrow.

2022-03-10 09:49 UTC, vasco-santos approved these changes

2022-03-10 09:53 UTC, merged