feat: js client accepts user provided fetch function
web3-storage/web3.storage pull request #1324
Opened 2022-05-16 09:49 UTC by duxiaofeng-github

I need to process some headers, like the cookie. because I post the request to my service and do some validation and then I create a proxy request to forward the request to your server. so, I need to add the `credentials: "include"` option to the `requestInit` option.

therefore, I add the `pre` middleware to achieve that, it will pass the requestInit to the user, and the user modifies and returns it to the client before the request is sent.

2022-05-17 09:38 UTC, duxiaofeng-github commented
can anyone do a review for this pr? @olizilla

2022-05-17 09:56 UTC, olizilla commented
Can you share a link to your code where you need this? It seems reasonable, but I just want to see the calling code to better understand what you need.

2022-05-17 10:09 UTC, olizilla commented
For example, if we land something like this, then perhaps we should just let the calling code pass in a custom `fetch` function. I think that would still work for what you need, and handle whatever intercepting other users might want to do in the future as well.

2022-05-18 18:31 UTC, olizilla commented
@duxiaofeng-github what do you think to letting the user pass in their own fetch function which could have full control over all the arguments passed to fetch.

2022-05-19 10:19 UTC, duxiaofeng-github commented
> For example, if we land something like this, then perhaps we should just let the calling code pass in a custom `fetch` function. I think that would still work for what you need, and handle whatever intercepting other users might want to do in the future as well.

it's not about the fetch function, it is about the args passed to fetch function. but yup, it can be done by passing the fetch function.

2022-05-19 10:27 UTC, duxiaofeng-github commented
> @duxiaofeng-github what do you think to letting the user pass in their own fetch function which could have full control over all the arguments passed to fetch.

so, that's what i have done, the pre function accept the  params which needed by the web3.storage, the user can modify them in pre function and return a new one, the return value will put into the fetch function.

2022-05-20 14:09 UTC, duxiaofeng-github commented
@olizilla 
here's my code snippet:
```
function makeStorageClient(token: string) {
  return new Web3Storage({
    token,
    endpoint: new URL("http://localhost:8082"),
    pre: (init: RequestInit) => {
      init.credentials = "include";

      if (init.headers != null) {
        const headers = new Headers(init.headers);
        headers.delete("Authorization");
        init.headers = headers;
      }

      return init;
    },
  });
}
```

2022-05-30 07:21 UTC, duxiaofeng-github commented
why is the ci always failed? @orvn

2022-05-30 09:53 UTC, olizilla requested changes
This is an interesting idea. If you have time to edit it so that a user may pass in a custom `fetch` function instead of a `pre`, and add a test then we can get this merged.

2022-05-31 05:13 UTC, duxiaofeng-github commented
ok, i can add a `customFetch` option, but what should I test for this case? should I just test the `customFetch` whether being executed?

2022-06-06 08:55 UTC, duxiaofeng-github commented
> This is an interesting idea. If you have time to edit it so that a user may pass in a custom `fetch` function instead of a `pre`, and add a test then we can get this merged.

@olizilla ok, i add a `customFetch` option already

2022-06-08 13:27 UTC, olizilla requested changes
Nice! Thanks for pushing this forward! As this will be part of the public api I'd like to rename `customFetch` to just `fetch`. I've provided some of the changes needed to land this as suggestions.

I think all that is left is to alias the fetch we import at the top of the file like

```js
import {
  fetch as _fetch,
  File,
  Blob,
  Blockstore
} from './platform.js'
```

2022-06-08 13:27 UTC, olizilla commented on packages/client/src/lib.js
> +      return await Web3Storage.putCar({ endpoint, token, rateLimiter, customFetch }, car, { onStoredChunk, maxRetries, maxChunkSize, name })
```suggestion
      return await Web3Storage.putCar({ endpoint, token, rateLimiter, fetch }, car, { onStoredChunk, maxRetries, maxChunkSize, name })
```

2022-06-08 13:27 UTC, olizilla commented on packages/client/src/lib.js
> +          const request = await (customFetch||fetch)(url.toString(), {
If we default fetch in the constructor, this line is neater
```suggestion
          const request = await fetch(url.toString(), {
```

2022-06-08 13:27 UTC, olizilla commented on packages/client/src/lib.js
> +  static async get ({ endpoint, token, rateLimiter = globalRateLimiter, customFetch }, cid) {
```suggestion
  static async get ({ endpoint, token, rateLimiter = globalRateLimiter, fetch = _fetch }, cid) {
```

2022-06-08 13:27 UTC, olizilla commented on packages/client/src/lib.js
> +      headers: Web3Storage.headers(token),
```suggestion
      headers: Web3Storage.headers(token)
```

2022-06-08 13:27 UTC, olizilla commented on packages/client/src/lib.js
> +    const res = await (customFetch||fetch)(url.toString(), {
```suggestion
    const res = await fetch(url.toString(), {
```

2022-06-08 13:27 UTC, olizilla commented on packages/client/src/lib.js
> +    async function listPage ({ endpoint, token, rateLimiter = globalRateLimiter, customFetch }, { before, size }) {
```suggestion
    async function listPage ({ endpoint, token, rateLimiter = globalRateLimiter, fetch = _fetch }, { before, size }) {
```

2022-06-08 13:27 UTC, olizilla commented on packages/client/src/lib.js
> +      return (customFetch||fetch)(url.toString(), {
```suggestion
      return fetch(url.toString(), {
```

2022-06-08 13:27 UTC, olizilla commented on packages/client/src/lib/interface.ts
> +  customFetch?: typeof fetch
```suggestion
  fetch?: typeof fetch
```

2022-06-08 13:27 UTC, olizilla commented on packages/client/test/custom-fetch.spec.js
> +    const client = new Web3Storage({ endpoint, token, customFetch })
```suggestion
    const client = new Web3Storage({ endpoint, token, fetch: customFetch })
```

2022-06-14 09:07 UTC, olizilla commented
@duxiaofeng-github Please run `npm run lint:fix` from the root of the project to fix the issues that Standard JS is reporting, and push the changes.

2022-06-16 10:20 UTC, duxiaofeng-github commented
@olizilla  it's done

2022-06-16 11:47 UTC, olizilla commented on packages/client/test/custom-fetch.spec.js
> +    await client.list()
`list()` returns `AsyncIterable`. The return value needs to be iterated to trigger a call to fetch

2022-06-16 18:19 UTC, duxiaofeng-github commented
@olizilla fixed

2022-06-17 09:47 UTC, olizilla commented
you can run the `lint` and `test` steps locally by running

```console
$ npm run lint

$ npm run test -w packages/client
```

you need docker running for the tests to set up the needed containers, but otherwise it should just work

2022-06-17 11:33 UTC, duxiaofeng-github commented
@olizilla it should works this time

2022-06-20 15:15 UTC, alanshaw approved these changes

2022-06-20 15:19 UTC, merged

2022-06-23 15:31 UTC, alanshaw commented
@duxiaofeng-github this has been released in v4.3.0