fix: upgrade wrangler
web3-storage/web3.storage pull request #1432
Opened 2022-06-09 08:17 UTC by vasco-santos

This PR upgrades wrangler to its v2. Simplifies API worker configuration ~~and allows us to deploy to cloudflare pages~~.

Some details on our wrangler migration also based on https://developers.cloudflare.com/workers/wrangler/migration/migrating-from-wrangler-1/

```
- 😶 Ignored: "type":
      Most common features now work out of the box with wrangler, including modules, jsx,
  typescript, etc. If you need anything more, use a custom build.
    - Deprecation: "build.upload.format":
      The format is inferred automatically from the code.
    - Deprecation: "build.upload.main":
      Delete the `build.upload.main` and `build.upload.dir` fields.
      Then add the top level `main` field to your configuration file:
      ```
      main = "dist/worker.mjs"
      ```
    - Deprecation: "build.upload.dir":
      Use the top level "main" field or a command-line argument to specify the entry-point for the
  Worker.
    - Unexpected fields found in top-level field: "watch_dir"
    - "env.staging" environment configuration
      - Deprecation: "zone_id":
        This is unnecessary since we can deduce this from routes directly.
```

~~Needed before merge:~~
- [ ] ~~Go to [CF Dashboard](https://dash.cloudflare.com/fffa4b4363a7e5250af8357087263b3a/pages/view/web3-storage/settings/builds-deployments) and change branch to main + disable automatic deploys~~

Closes #1399

2022-06-09 13:52 UTC, olizilla commented
> Go to [CF Dashboard](https://dash.cloudflare.com/fffa4b4363a7e5250af8357087263b3a/pages/view/web3-storage/settings/builds-deployments) and change branch to main + disable automatic deploys

Does this mean that we won't have a preview pages deploy for the main branch? We currently get a pages build for main which I use when I'm looking for the latest staging deploy. 

We'd really like a way to tell CF to build main and deploy it as "staging.web3.storage", but this has been difficult to do externally as we'd have to wait until the CF pages build finishes and then update the dns record

2022-06-09 14:44 UTC, olizilla commented
My minor concern here is just that if we do the change to how the website gets deployed, then we would lose the cloudflare preview deployment for the main branch.

We could just leave the `website-prod` branch trick in place, as it seems to work well.

2022-06-09 14:48 UTC, olizilla commented
An alternative option for website deploying:
- Create a `staging.web3.production` site in CF Pages. Set that up to auto build all and any branches. and set main as the "production" branch, which updates staging.web3.production
- Update `web3.production` in CF pages to disabled auto-builds, and disconnect the repo. Only use the CLI to publish the website from CI.

Pro: gets us a staging deployment
Con: prod and staging deploys are significantly different.

2022-06-09 14:50 UTC, olizilla requested changes
Rad!

2022-06-09 14:50 UTC, olizilla commented on .github/workflows/website.yml
> +        run: npx wrangler pages publish --project-name web3-storage --branch main ./packages/website/out
Unless there is something I am missing here, I think we should revert this for now, and focus on upgrading wrangler in this PR. We (I) can bikeshed on the website deployment process as a seperate issue

2022-06-10 09:47 UTC, vasco-santos commented
@olizilla sounds good, I will revert website changes and we can talk about them in an issue for now

2022-06-13 21:26 UTC, olizilla approved these changes
👍

2022-06-14 08:37 UTC, merged