Increase timeout for pins cron
web3-storage/web3.storage pull request #2174
Opened 2022-12-30 14:43 UTC by ericssontadashi

2022-12-30 15:11 UTC, dchoi27 approved these changes

2022-12-31 13:52 UTC, vasco-santos requested changes

2022-12-31 13:52 UTC, vasco-santos commented on .github/workflows/cron-pins.yml
> -    timeout-minutes: 30
it will run each 30 minutes, so we will start having multiple jobs at same time. See line 5

2023-01-03 13:56 UTC, vasco-santos approved these changes

2023-01-03 15:20 UTC, olizilla commented
The cron job to update pin status is set up so it basically runs all the time. It times out after 30mins and runs every 30mins. We can move it to run for 60mins and timeout every 60mins but it's basically the same. The idea is that the job picks up where it left off, updating the db as it goes, so the interval isn't too important. The key point is we expect the job to timeout out most of the time. The subsequent run just picks up where it left off.

2023-01-03 15:53 UTC, vasco-santos commented
@olizilla that might have been true at some point. However, we did do changes in the past to make it not the case anymore. Like moving heavy queries to the replica and removing Pin status remote rows.

If you see the github action, it even has an heartbeat which will throw alerts in case of failures. I agree that moving 30-60 minutes might be the same, and we probably just need to get some backlog catched up.

2023-01-03 15:58 UTC, alanshaw commented
Also github cron is approximate and often starts after the scheduled time, increasing the run time should reduce the number of periods when we're waiting on github to start the job, giving us more time to process.

2023-01-03 15:58 UTC, merged