feat: add tooltip to the pin status
web3-storage/web3.storage pull request #474
Opened 2021-09-14 16:07 UTC by jdiogopeixoto

- Adds a tooltip to the pin status with useful information 

Closes #429

2021-09-17 16:33 UTC, rafaelramalho19 requested changes

2021-09-17 16:42 UTC, jdiogopeixoto commented on packages/website/pages/files.js
> + * @param {string} pinStatus
You're right! Done 👍

2021-10-06 13:12 UTC, zebateira requested changes

2021-10-06 13:14 UTC, jdiogopeixoto commented on package-lock.json
> +<<<<<<< HEAD
My bad, missed that one!

2021-10-06 13:17 UTC, zebateira approved these changes

2021-10-06 13:22 UTC, merged