feat: improve tokens table
web3-storage/web3.storage pull request #483
Opened 2021-09-20 16:57 UTC by jdiogopeixoto

- Shortens the token and prevents it from wrapping
- Improves the table responsiveness

![image](https://user-images.githubusercontent.com/34691925/134042203-b0c431f4-20a8-4d30-99dd-0bf1d837e2db.png)

![image](https://user-images.githubusercontent.com/34691925/134042216-33911835-2c28-4c2d-9695-ab60b1846959.png)

Closes #455

2021-09-21 15:29 UTC, olizilla approved these changes

2021-09-21 15:51 UTC, zebateira requested changes
Looks great! Just two details and done 👍

2021-09-21 15:51 UTC, zebateira commented on packages/website/pages/tokens.js
> +          {token.secret.substr(0, 20)}...{token.secret.substr(token.secret.length - 20, token.secret.length)}
Could we move the `20` to a computed property of the component?
Easier to use and tweak this value.

2021-09-21 15:51 UTC, zebateira commented on packages/website/pages/tokens.js
> +                    {tokens.map((t, i) =>
```suggestion
                    {tokens.map((token, index) =>
```

2021-09-22 13:32 UTC, zebateira approved these changes

2021-09-22 13:37 UTC, rafaelramalho19 approved these changes

2021-09-22 15:15 UTC, merged