Chore/improve docs
web3-storage/web3.storage pull request #607
Opened 2021-11-11 18:33 UTC by flea89

Tiny PR with 
- some documentation for dealing with updating schemas
- improved db cli error logging

2021-11-11 19:25 UTC, vasco-santos requested changes

2021-11-11 19:25 UTC, vasco-santos commented on packages/db/postgres/README.md
> +If you're creating a new table, type or view please remember to update `reset.sql` as well.
```suggestion
If you're creating a new table, type or view please remember to update `reset.sql` as well.

```

2021-11-11 19:25 UTC, vasco-santos commented on packages/db/postgres/README.md
> +In order for your changes to the DB schema to be reflected in Postgres you need to run:
```suggestion

In order for your changes to the DB schema to be reflected in Postgres you need to run an `openapi-typescript` script:
```

2021-11-12 12:26 UTC, flea89 reviewed
Thanks for the suggestions @vasco-santos . Accepted

2021-11-12 14:15 UTC, vasco-santos approved these changes

2021-11-12 14:38 UTC, merged