[WIP] Issue 703 - Navigation Links the Nextjs way
web3-storage/web3.storage pull request #716
Opened 2021-11-29 22:37 UTC by dashcraft

Fixed navigation links, there where some other consistency updates:
- Navigation Links are handled by nextjs router/link component
- Styles for navbar made consistent during loading so it's not flashing white
- Added the maintenance banner to loading so the navigation bar doesn't move when loading
- Updated page background color to be consistent with navbar color during loading screen

I need to test this for logged in users, this is a WIP until that's been tested and reviewed.

2021-11-30 21:50 UTC, the-simian requested changes
I checked this out - make sure that if you're on a particular route, the nav item for that route is inert. (eg. if you're on home, clicking home should do nothing)

2021-11-30 22:20 UTC, redaphid commented on packages/website/components/navbar.js
> +              <a onClick={onLinkClick} className={clsx('text-sm text-w3storage-purple font-bold no-underline hover:underline align-middle', item.spacing)}>
Shouldn't the `onClick` be on the `<Link>`  element?

2021-11-30 22:22 UTC, redaphid commented on packages/website/components/navbar.js
> +              <a onClick={onLinkClick} className={clsx('text-sm text-w3storage-purple font-bold no-underline hover:underline align-middle', item.spacing)}>
nvm

2021-11-30 22:42 UTC, redaphid approved these changes
Looks good to me!

2021-12-01 01:56 UTC, the-simian approved these changes
Navigation is much tighter now, much improved!

2021-12-01 15:03 UTC, merged