fix: change filecoin storage to web3 storage in client
web3-storage/web3.storage pull request #9
Opened 2021-06-30 18:09 UTC by vasco-santos

2021-06-30 19:12 UTC, vasco-santos commented
The API test is failling everywhere, but not locally for me. We need to figure this out tomorrow

2021-07-01 08:56 UTC, olizilla commented
Agree, issue is here for CI fails https://github.com/web3-storage/web3.storage/issues/11

2021-07-01 08:58 UTC, olizilla requested changes
renaming stuff is harder than it sounds

2021-07-01 08:58 UTC, olizilla commented on packages/client/README.md
> +import { WebStorage } from 'web3.storage'
```suggestion
import { Web3Storage } from 'web3.storage'
```

2021-07-01 08:58 UTC, olizilla commented on packages/client/README.md
> +const client = new WebStorage({ token: apiKey })
```suggestion
const client = new Web3Storage({ token: apiKey })
```

2021-07-01 10:08 UTC, olizilla approved these changes

2021-07-01 10:08 UTC, merged